version: '2'

services:

  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports: 
     - 9200:9200
     - 9300:9300
    environment:
     - discovery.type=single-node
 
  connect:
    image: slalit360/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    links:
     - zookeeper
     - kafka
     - mysql
     - elastic
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
 
  kibana:
    image: elastic/kibana:7.7.0
    ports: 
     - 5601:5601
    links:
     - elastic
    environment:
     - ELASTICSEARCH_HOSTS=http://elastic:9200
