version: '2'

services:

  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
 
  connect:
    image: slalit360/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    links:
     - zookeeper
     - kafka

    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
 
    volumes:
     - cdc-connect:/kafka/logs
     - cdc-connect:/kafka/config
     - cdc-connect:/kafka/data

  kibana:
    image: elastic/kibana:7.7.0

    ports: 
     - 5601:5601
    environment:
     - ELASTICSEARCH_HOSTS=http://elasticsearch.moeving.dev:9200


volumes:
  cdc-connect:
    driver: local
